name: Deployment File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            3.1.x
            5.0.x

      - name: Restore dotnet
        run: dotnet restore

      - name: Build application
        run: dotnet build -c Release --no-restore

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: <your-aws-region>

      - name: Deploy to AWS Elastic Beanstalk
        run: |
          eb init -p <your-platform> <your-application-name>
          eb create <your-environment-name>
